### ISSUE TITLE
Migration time to React 17

### ISSUE THREAD

**Issue by Aleksey-Danchin** [inlet/react-pixi#308] opened 2021-07-03 06:25 UTC
### Description

it's time to transfer the project to react 17.

### Steps to reproduce

`npm install @inlet/react-pixi`

### Additional info

- `@inlet/react-pixi` version: 6.6.2
- `React` version: 17.0.2
- `ReactDOM` version: 170.2
- `PIXI` version: ^5

```
old@old-computer:~/Desktop/react-pixi-game$ npm install pixi.js @inlet/react-pixi
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"*" from @testing-library/react@11.2.7
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^11.2.7" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"*" from @testing-library/react@11.2.7
npm ERR!     node_modules/@testing-library/react
npm ERR!       @testing-library/react@"^11.2.7" from the root project
npm ERR!     react-dom@"^17.0.2" from the root project
npm ERR!     1 more (@inlet/react-pixi)
npm ERR!   5 more (react-scripts, the root project, @inlet/react-pixi, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-reconciler@0.20.4
npm ERR! node_modules/react-zdog/node_modules/react-reconciler
npm ERR!   react-reconciler@"^0.20.4" from react-zdog@1.0.11
npm ERR!   node_modules/react-zdog
npm ERR!     peer react-zdog@">=1.0" from @react-spring/zdog@9.2.3
npm ERR!     node_modules/@react-spring/zdog
npm ERR!       @react-spring/zdog@"~9.2.0" from react-spring@9.2.3
npm ERR!       node_modules/react-spring
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/old/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/old/.npm/_logs/2021-07-03T06_16_13_750Z-debug.log
```

**Comment by inlet** [comment] 2021-07-03 07:36
Can you be more specific? 

This works up to the latest stable release of React.

Try installing in a clean folder to isolate the problem. What node version are you on?

I’ll close this issue as I cannot reproduce this issue

**Closed by inlet** 2021-07-03 07:36 UTC

**Comment by Aleksey-Danchin** [comment] 2021-07-03 07:55
https://www.loom.com/share/69ae900611374f07845a20915c83b0aa

**Comment by inlet** [comment] 2021-07-03 08:04
Sorry the link doesn’t work

**Comment by Aleksey-Danchin** [comment] 2021-07-03 08:11
https://www.loom.com/share/8a70b45746f648ca96a482e6a1b41a10

**Comment by inlet** [comment] 2021-07-03 08:49
Super weird, does it work when installing in a clean folder? 

Can you please try:

Remove the package lock and installing

or

installing it with yarn

**Comment by inlet** [comment] 2021-07-05 09:41
Hi @Aleksey-Danchin,

I just want to let you know that I've fixed this, you can now import the package correctly with:

```
npm install @inlet/react-pixi
```

Thanks!
