### ISSUE TITLE
Typescript says 'width' isn't allowed on <Stage />

### ISSUE THREAD

**Issue by Heilemann** [inlet/react-pixi#342] opened 2022-05-06 16:25 UTC
### Description

Seeing this typescript error on Stage, but it doesn't make sense to me? Pretty sure Stage is supposed to take a width. [The documentation page for it](https://reactpixi.org/stage) says so at least.

<img width="1235" alt="CleanShot 2022-05-06 at 12 20 08@2x" src="https://user-images.githubusercontent.com/203049/167172715-b85d3262-ab95-4cfe-b25c-6c313b2ed5aa.png">

### Additional info

- `@inlet/react-pixi` version: 6.6.5
- `React` version: 17.0.2
- `ReactDOM` version: 17.0.2
- `PIXI` version: 6.2.2

**Comment by inlet** [comment] 2022-05-06 17:30
Are you using @types/react v 18 perhaps?

**Comment by Heilemann** [comment] 2022-05-06 17:31
Doesn't look like it, from my package.json: `"@types/react": "^17.0.37",`

**Comment by inlet** [comment] 2022-05-20 10:21
![image](https://user-images.githubusercontent.com/232559/169507752-307654d0-ef33-44cf-b53c-9cad7db48c9f.png)

Unfortunately I cannot reproduce the issue.. it's working as expected:

![image](https://user-images.githubusercontent.com/232559/169508197-0bfea669-36c7-441a-bbb5-9d34af2aab7f.png)

**Comment by inlet** [comment] 2022-05-20 10:22
Closing the issue as I cannot reproduce this, please let me know if and why we should reopen this issue. Thanks!

**Closed by inlet** 2022-05-20 10:21 UTC

**Comment by inlet** [comment] 2022-05-20 10:23
Maybe your typescript settings are incorrect? can you check your `tsconfig.json`

**Comment by Heilemann** [comment] 2022-05-20 10:58
Looks like this:

`{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
`

**Comment by inlet** [comment] 2022-05-20 10:59
Can you try a CRA?
