### ISSUE TITLE
useTick use too many resource 

### ISSUE THREAD

**Issue by toreal** [inlet/react-pixi#274] opened 2021-01-07 14:58 UTC
### Description

I try to make an animation as following. But it will use too many memory resources to make Chrome crashed.
[https://youtu.be/73x6a7oOU98](https://youtu.be/73x6a7oOU98)

[](url)

### Steps to reproduce

```
import React, { useState,useCallback } from 'react';
import { Sprite } from '@inlet/react-pixi';
import { useTick } from '@inlet/react-pixi'
import { Graphics, Container } from '@inlet/react-pixi';
import DOTDATA from './dot.json'
let count =0;
let points: {x: number, y: number} [][] = DOTDATA;
function Hand(){
    const [x, setX] = useState(0);
    const [y, setY] = useState(0);
    const mask = React.useRef(null);
    const draw = useCallback((g) => {
        g.lineStyle(10,0x000000).moveTo(x,y)
        .drawCircle(x,y,10);
            }, [x,y]);
    useTick(delta => {
        count=count+1;
      if ( count < (points[0].length))
        {
         let px:number = points[0][count].x/2;
        let py:number = points[0][count].y/2;
        setX(px);       
        setY(py);
        }else if ( count > (points[0].length) &&  (count -points[0].length) <  (points[1].length))
        {
        let px:number = points[1][(count-points[0].length)].x/2;
        let py:number = points[1][(count-points[0].length)].y/2;
        setX(px);       
        setY(py);  
        }else if ( count >(points[0].length+points[1].length) &&  (count-points[0].length-points[1].length ) < points[2].length )
        {
            let px:number = points[2][(count-points[0].length-points[1].length)].x/2;
            let py:number = points[2][(count-points[0].length-points[1].length)].y/2;
            setX(px);       
            setY(py);
    }
      })
    return (
     <Container >    
        <Sprite image="./good.jpg" x={0} y={0} width={610/2} height={567/2}   mask={mask.current} />
         <Graphics draw={draw} ref={mask}   /> 
        <Sprite image="./hand.png" x={x} y={y} width={100} height={120} />
      </Container>
)
}
export default Hand;

```

### Additional info

- `@inlet/react-pixi` version: 6.0.6
- `React` version: 17.0.1
- `ReactDOM` version: 17.0.1
- `PIXI` version: 5.3.7

**Comment by inlet** [comment] 2021-01-07 15:12
Can you please share a codepen/codesandbox example with this so I can have a look at it.

`useTick` uses PIXI's shared ticker, nothing fancy here. I don't know what your `DOTDATA` looks like, but keep in mind that iterating over each point in a game loop might be expensive. At least that is something I'd look first in order to pinpoint the issue.

I'll close this issue for now as I'm most certain the `useTick` is not the cause (I use it all the time), if you believe otherwise I'm happy to reopen it.

**Closed by inlet** 2021-01-07 15:12 UTC

**Comment by toreal** [comment] 2021-01-08 08:29
Thank you for your quick reply.
I have implemented a sample in codepen. 
Please take a look. 
I am not sure what happened, But I saw a lot of _tick in the call stack. 
Could you kindly point me a direction on how to solve this problem? 
Thanks.
[image of call stack ](https://www.flickr.com/photos/191693082@N04/50813142391/in/shares-3J7yP8/)

[codepen sample](https://codepen.io/toreal/pen/vYXrqGr)

**Comment by inlet** [comment] 2021-01-08 12:17
Although I haven't got much time to dig into your code, I forked it and changed the code a little so it doesn't crash. Now we're updating xy all together in a single call and within a setState callback.

The animation runs but it contains some js errors as you can see in the console.

Hopefully this helps you!

https://codepen.io/inlet/pen/c1a178549e1a24da5bc1a92ab03dc314?editors=1010

**Comment by toreal** [comment] 2021-01-08 13:43
Thank you for your time to dig into my code.  However, since the js error, the code did not run to the crash point. I already correct the js error and the code still crashed as before.

[https://codepen.io/toreal/pen/vYXrqGr](https://codepen.io/toreal/pen/vYXrqGr)

**Comment by inlet** [comment] 2021-01-08 14:17
Sure, you're welcome! 

You're right I think I forgot to implement some if-statements from continuing the animation. However, the execution of the code in `useTick` is responsible for crashing the app. Maybe referring to pointers that are not there?

Just to demo that useTick works as expected, I created a little physics demo (to help someone out on Slack):

https://codepen.io/inlet/pen/da2813628e1a45313154c6ee4e1077e7

**Comment by toreal** [comment] 2021-01-08 14:57
When I use Safari, sometimes it has the chance to finish the animation.  Meanwhile, it will display a lot of memory being used by this program.  Thus, it may not be the null pointer case. I think "useTick" works fine, but the function is fired at a fixed rendering rate. Thus, if we work on many things in this function that will make the system has a lot of unfinished jobs waiting in the queue to confirm.  Do you have any suggestions or other alternative methods that will be better to implement the animation?
Thanks again.

**Comment by inlet** [comment] 2021-01-08 15:28
> but the function is fired at a fixed rendering rate.

The PIXI.Ticker uses requestAnimationFrame and waits for the browser to render

> Thus, if we work on many things in this function that will make the system has a lot 

Performance-wise it's always good to keep the logic in the game loop as "cheap" as possible.

> Do you have any suggestions or other alternative methods that will be better to implement the animation?

Given the fact that it does run correctly in the first sequence, try to find and debug why it crashes the remaining part of the animation.

**Comment by toreal** [comment] 2021-01-08 16:01
Thank you for being such an inspiration. I will continue to keep trying.

**Comment by inlet** [comment] 2021-01-08 16:19
Thanks and you're most welcome :wink:

Good luck!
