### ISSUE TITLE
Could not find ID for fiber

### ISSUE THREAD

**Issue by AdrienLemaire** [inlet/react-pixi#322] opened 2022-02-03 08:36 UTC
### Description

Using React Developer Tools 4.23.0 (1/24/2022), I cannot debug the props and hooks of components that fall within react-pixi's fiber tree.

![](https://i.imgur.com/zlOyTrR.png)

### Additional info

- `@inlet/react-pixi` version: 6.6.3
- `React` version: 17.0.2
- `ReactDOM` version: 17.0.2
- `PIXI` version: 6.1.1

**Comment by inlet** [comment] 2022-02-03 10:38
[This demo](https://cdpn.io/pen/debug/yLVmPWv) works as expected, not sure why yours isn't working though.

This demo uses:

- `PIXI`version: 6.0.0
- `React` version: 17.0.2
- `ReactDOM`: version 17.0.2
- `@inlet/react-pixi`: version 6.6.5

Can you try updating `@inlet/react-pixi`?

**Comment by inlet** [comment] 2022-02-06 22:48
I’ll close this issue for now as I cannot reproduce it. Let me know if we need to reopen this issue

**Closed by inlet** 2022-02-06 22:48 UTC
