### ISSUE TITLE
Consumer inside Stage

### ISSUE THREAD

**Issue by seimsel** [inlet/react-pixi#55] opened 2018-10-24 04:45 UTC
### Description
Consumer inside Stage doesn't update.

### Steps to reproduce
```
import * as React from 'react';
import { Stage, Text } from '@inlet/react-pixi';

const defaultValue = { 
    data: 0
};
const Context = React.createContext<any>(defaultValue);

export default class App extends React.Component<any, any> {
    constructor(props: any) {
        super(props);
        this.state = defaultValue
    }

    componentDidMount() {
        setInterval(() => {
            this.setState({
                data: this.state.data + 1
            })
        }, 1000)
    }

    render() {
        return (
            <Context.Provider
                value={this.state}
            >
                <Context.Consumer>
                    {({data}) => (
                        <>
                            <p>This works: {data}</p>
                            <Stage
                                options={{ 
                                    backgroundColor: 0xffffff,
                                    antialias: true,
                                    resolution: window.devicePixelRatio,
                                }}
                            >
                                <Context.Consumer>
                                    {({data}) => (
                                        <Text text={`This doesn't: ${data}`} />
                                    )}
                                </Context.Consumer>
                            </Stage>
                        </>
                    )}
                </Context.Consumer>
            </Context.Provider>
        );
    }
}
```

### Additional info

- `@inlet/react-pixi` version: 0.1.7
- `React` version: 16.5.2
- `ReactDOM` version: 16.5.2
- `PIXI` version: 4.8.2

**Comment by inlet** [comment] 2018-10-25 15:48
Hi @seimsel,

The React's Context API should work with React-PIXI. Could you create a codepen example (or something) to demonstrate this behaviour? 

Thanks!

**Comment by inlet** [comment] 2018-10-28 10:02
I'm closing this issue as I'm not able to reproduce it. 

Could you create an example in codepen/codesandbox/something to pinpoint the issue? Thanks!
Let's reopen this issue later on. Thanks for contributing..

ps. feel free to open a PR with a fix

**Closed by inlet** 2018-10-28 10:02 UTC
