### ISSUE TITLE
TSLint error

### ISSUE THREAD

**Issue by scq000** [inlet/react-pixi#343] opened 2022-06-06 12:24 UTC
### Description
When I use the demo in my code, the following error shows by tslint:

```
TS2322: Type '{ children: Element; x: number; y: number; }' is not assignable to type 'IntrinsicAttributes & Partial<Omit<PIXI.Container, any> & WithPointLike<P>> & InteractionEvents & { ref?: Ref<...> | undefined; } & { ...; }'.
  Property 'x' does not exist on type 'IntrinsicAttributes & Partial<Omit<PIXI.Container, any> & WithPointLike<P>> & InteractionEvents & { ref?: Ref<...> | undefined; } & { ...; }'.
    40 |     <div>
    41 |       <Stage width={300} height={300} options={{ backgroundAlpha: 0 }}>
  > 42 |         <Container x={150} y={150}>
       |                    ^
    43 |           <Bunny />
    44 |         </Container>
    45 |       </Stage>

```

### Additional info

- `@inlet/react-pixi` version: 6.8.0
- `React` version: 17.0.44
- `ReactDOM` version: 17.0.16
- `PIXI` version: 6.4.2

**Comment by scq000** [comment] 2022-06-06 12:32
And I found when I config the `module` item to "commonjs" in `tsconfig.json` file, the error has been disappeared.  And now the value of `module` item in my project is "esnext".

**Comment by inlet** [comment] 2022-06-14 08:13
Unfortunately I cannot reproduce this issue, are you using React 18 types perhaps?

**Comment by akkadaska** [comment] 2022-07-11 12:50
I found the same issue and resolved by making the react and also **its types** versions from 18 to 17.0.2.
Please make sure you don't use not only react version 18 but also @types/react version 18 as @LeoTheG mentioned.

**Comment by inlet** [comment] 2022-07-12 12:32
I close this issue as this is related to React 18, see #337

**Closed by inlet** 2022-07-12 12:32 UTC
