### ISSUE TITLE
Context update does not travel from DOM to Pixi renderer 

### ISSUE THREAD

**Issue by RodrigoHamuy** [inlet/react-pixi#165] opened 2019-11-13 14:52 UTC
### Description

When you create a context outside of the Pixi Stage, its value does not update inside the Pixi Stage.

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-pixi-context-example-eky26

### Expected

`PixiComponent` should render `Context value: 15`.

### Currently

`PixiComponent` renders `Context value: undefined`.

### More info

Compare `PixiComponent` with `PixiComponentWithMiddleContext`. 

`PixiComponentWithMiddleContext` does render the context value because it has a middleware `MyPixiContext` inside the stage. 

Without this, any component inside `Stage` can't access `MyContext` latest value and only receives the value used when it was instantiated.

**Comment by inlet** [comment] 2019-11-13 15:08
Duplicate of #77

**Closed by inlet** 2019-11-13 15:08 UTC
